require: rubocop-rspec

AllCops:
  NewCops: enable
  DisplayStyleGuide: true

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - db/schema.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

# Lint/NonDeterministicRequireOrder:
#   Exclude:
#     - spec/rails_helper.rb
