require: rubocop-rspec

AllCops:
  NewCops: enable
  DisplayStyleGuide: true

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/simple_form_bootstrap.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - config/environments/*.rb
    - db/schema.rb
    - config/environments/*.rb
    - config/initializers/simple_form_bootstrap.rb
    - app/admin/books.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - spec/sections/billing_address_form.rb
    - spec/sections/shipping_address_form.rb

Style/SymbolProc:
  Exclude:
    - app/admin/books.rb
