require: rubocop-rspec

AllCops:
  NewCops: enable
  DisplayStyleGuide: true

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/simple_form_bootstrap.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - config/environments/*.rb
    - db/schema.rb
    - config/environments/*.rb
    - config/initializers/simple_form_bootstrap.rb
    - app/admin/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Style/SymbolProc:
  Exclude:
    - app/admin/books.rb

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

RSpec/LetSetup:
  Exclude:
    - spec/features/*.rb
