version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: BookStore
    docker:
      - image: circleci/ruby:2.7.1
      - image: circleci/postgres:9.6.9
        environment:
            POSTGRES_USER: yusha
            POSTGRES_DB: book_store_test
            POSTGRES_PASSWORD: "daniil200013"

caches:
  - &bundle_cache_full v1-refactoring_example-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v1-refactoring_example

commands:
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: *bundle_cache_full
      - run: yarn install --check-files
      - run: bundle exec rails db:schema:load --trace
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_specs:
    description: command to run specs
    steps:
      - run:
          name: run specs
          command: bundle exec rspec

jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs

workflows:
  version: 2
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
