version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: Book-store
    docker:
      - image: circleci/ruby:2.7.1
caches:
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}
commands:
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs

workflows:
  version: 2
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
