default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.db[:username] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_store_development
  password: <%= Rails.application.credentials.db[:password] %>

test:
  <<: *default
  database: book_store_test
  password: <%= Rails.application.credentials.db[:password] %>

# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: book_store_production
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
