require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")

require("jquery")
require("bootstrap-sass")
require ("@fortawesome/fontawesome-free/js/all.min")
require("typeface-open-sans")

require("packs/book/read_more")
require("packs/book/review_rating")
require("packs/catalog/pagination")
require("packs/users/remove_account_checkbox")
require("packs/users/reset_password")
require("packs/flash")
