require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")

require("jquery")
require("bootstrap-sass")
require ("@fortawesome/fontawesome-free/js/all.min")
require("typeface-open-sans")

require("packs/custom/users/remove_account_checkbox")
require("packs/custom/users/password")
require("packs/custom/book")
require("packs/custom/books")
require("packs/custom/flash")
require("packs/custom/review_rating")
